name: Build for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.102'
  PluginSolutionPath: 'src\Plugin.Maui.BottomSheet\Plugin.Maui.BottomSheet.sln'
  Configuration: 'Release'

jobs:
  Build-Plugin_Maui_BottomSheet:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install .NET MAUI Workload
      run: dotnet workload restore ${{ env.PluginSolutionPath }}

    - name: Build Plugin.Maui.BottomSheet
      run: dotnet build ${{ env.PluginSolutionPath }} -c ${{ env.Configuration }}

